In [48]:
import pandas as pd

In [49]:
df=pd.read_csv("train.csv")
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [50]:
df.tail()

id  ... label
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[5 rows x 5 columns]

In [51]:
df.shape

(20800, 5)

In [52]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [53]:
### Removing Nan Values
df=df.dropna()

In [54]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [55]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [56]:

df.tail()

id  ... label
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[5 rows x 5 columns]

In [57]:
df.shape

(18285, 5)

In [58]:
x=df.drop('label',axis=1)
y=df['label']

In [59]:
x.shape

(18285, 4)

In [60]:
y.shape

(18285,)

In [61]:
### Importing Tensorflow
import tensorflow as tf
tf.__version__

'2.3.0'

In [62]:
#### Importing Keras Libraries
from tensorflow.keras.layers import Embedding
### Use for add pading(before or after) to Lstm Embedding Layer
from tensorflow.keras.preprocessing.sequence import pad_sequences
####for converting sentences to one_hot representation given Vocabulary Size
from tensorflow.keras.preprocessing.text import one_hot
### for model
from tensorflow.keras.models import Sequential
#### Lstm and Dense Layer
from tensorflow.keras.layers import LSTM,Dense

In [63]:
### Vocabulary Size
vocab_size=5000

In [64]:
### making copy of x data
msg=x.copy()

In [65]:
msg.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [66]:
### Reseting data because first we had deleted nan values
msg.reset_index(inplace=True)

In [67]:
msg.tail()

index  ...                                               text
18280  20795  ...  Rapper T. I. unloaded on black celebrities who...
18281  20796  ...  When the Green Bay Packers lost to the Washing...
18282  20797  ...  The Macy’s of today grew from the union of sev...
18283  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
18284  20799  ...    David Swanson is an author, activist, journa...

[5 rows x 5 columns]

In [68]:
msg.head()

index  ...                                               text
0      0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1      1  ...  Ever get the feeling your life circles the rou...
2      2  ...  Why the Truth Might Get You Fired October 29, ...
3      3  ...  Videos 15 Civilians Killed In Single US Airstr...
4      4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 5 columns]

In [69]:
msg.shape

(18285, 5)

In [70]:
#### Importing nltk libraries
import nltk
import re
from nltk.corpus import stopwords ### used for removing unnecessary data from text.

In [71]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [72]:
#### Data Preprocessing

###Stemming:- is the process of reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words known as a lemma

### Stemming we used PorterStemmer
from nltk.stem.porter import PorterStemmer
porter=PorterStemmer()
corpus=[]
for i in range(0,len(msg)):
  print(i)
  review=re.sub('[^a-zA-Z]'," ",msg['title'][i]) #### replacing all values except a-zA-Z characters with " "(blank space)
  review=review.lower()  #### Putting all reviews in lower case
  review=review.split() ### splitting reviews in words for applying stopwords 

  review=[porter.stem(words) for words in review if not words in stopwords.words('english')] ### stemming done onwords which are not match with stopwords
  review=' '.join(review) #### joining of words are done here
  corpus.append(review) ### Appending 



Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [73]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [74]:
len(corpus)

18285

In [75]:
#### One_hot process
onehot_repr=[one_hot(word,vocab_size) for word in corpus] ###Giving each word from corpus list for one_hot 
onehot_repr

[[487, 4204, 3942, 1770, 1236, 3583, 4642, 4655, 2971, 3793],
 [4023, 1167, 4642, 1566, 3707, 4800, 445],
 [1843, 735, 4690, 4148],
 [4008, 1216, 1238, 1564, 1003, 4822],
 [1866, 3707, 1160, 2051, 72, 1885, 3707, 148, 3094, 4411],
 [3383,
  1221,
  3712,
  1639,
  680,
  3041,
  1214,
  1043,
  4014,
  841,
  2255,
  1885,
  3942,
  925,
  445],
 [4454, 1463, 207, 2796, 4199, 999, 1929, 339, 3594, 3809, 180],
 [3578, 785, 60, 382, 961, 2509, 3041, 357, 3594, 3809, 180],
 [4910, 3888, 667, 1038, 2268, 3387, 3503, 2041, 3041, 356],
 [1353, 4054, 3864, 1264, 2840, 199, 4303, 3860],
 [2194, 1131, 823, 643, 2892, 1687, 1289, 3432, 4895, 3672, 1760],
 [1564, 1400, 1236, 3387, 3041, 961],
 [784, 75, 395, 3986, 1718, 75, 129, 4720, 1320],
 [4436, 1910, 4991, 3049, 4171, 3228, 2846, 3594, 3809, 180],
 [3513, 2064, 3772, 1398, 2259, 3594, 3809, 180],
 [3638, 114, 3269, 106, 2239, 4822, 3848, 1539, 1765, 2323],
 [2347, 3651, 1167],
 [4987, 145, 2653, 2506, 3041, 3745, 4503, 445],
 [1467, 1036, 46

# **Embedding Representation**

In [76]:
sent_length=20
### giving length 20 for array rows
### padding added for making sentences equal length
#### padding='pre' means add padding prefix hence 0 added for remaining columns
embedded_docs=pad_sequences(onehot_repr,maxlen=sent_length,padding='pre')
embedded_docs

array([[   0,    0,    0, ..., 4655, 2971, 3793],
       [   0,    0,    0, ..., 3707, 4800,  445],
       [   0,    0,    0, ...,  735, 4690, 4148],
       ...,
       [   0,    0,    0, ..., 3594, 3809,  180],
       [   0,    0,    0, ...,  157, 3675, 1375],
       [   0,    0,    0, ..., 3506, 4702, 3403]], dtype=int32)

In [77]:
len(embedded_docs)

18285

In [78]:
print(onehot_repr[0])

print(embedded_docs[0] )

[487, 4204, 3942, 1770, 1236, 3583, 4642, 4655, 2971, 3793]
[   0    0    0    0    0    0    0    0    0    0  487 4204 3942 1770
 1236 3583 4642 4655 2971 3793]


In [79]:
#### Creating Model

### Embedding Layer take input and convert into specific number of Feature of vectors
embedding_vector_feature=40
model=Sequential()
### Embedding Layer
model.add(Embedding(vocab_size,embedding_vector_feature,input_length=sent_length))
### Adding Lstm layer
model.add(LSTM(100))
### Addin Dense Layer because its classification problem
model.add(Dense(units=1,activation='sigmoid')) #### units =1 because it is classification problem and return 1 value either 0 or 1
### Model Compilation 
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy']) 
### model Summary
model.summary()



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [80]:
print(len(embedded_docs))
y.shape

18285


(18285,)

In [81]:
import numpy as np


In [82]:
#### Putting all embedded_docs values in x_final
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [83]:
x_final

array([[   0,    0,    0, ..., 4655, 2971, 3793],
       [   0,    0,    0, ..., 3707, 4800,  445],
       [   0,    0,    0, ...,  735, 4690, 4148],
       ...,
       [   0,    0,    0, ..., 3594, 3809,  180],
       [   0,    0,    0, ...,  157, 3675, 1375],
       [   0,    0,    0, ..., 3506, 4702, 3403]], dtype=int32)

In [84]:
y_final

array([1, 0, 1, ..., 0, 1, 1])

In [85]:
x_final.shape

(18285, 20)

In [86]:
y_final.shape

(18285,)

# **Model Training**

In [87]:
### Splitting Data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.33)

In [88]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 5s 27ms/step - loss: 0.3272 - accuracy: 0.8446 - val_loss: 0.1901 - val_accuracy: 0.9191
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1431 - accuracy: 0.9433 - val_loss: 0.1823 - val_accuracy: 0.9229
Epoch 3/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1032 - accuracy: 0.9626 - val_loss: 0.2029 - val_accuracy: 0.9208
Epoch 4/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0750 - accuracy: 0.9738 - val_loss: 0.2181 - val_accuracy: 0.9215
Epoch 5/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0535 - accuracy: 0.9832 - val_loss: 0.2800 - val_accuracy: 0.9176
Epoch 6/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0311 - accuracy: 0.9901 - val_loss: 0.3090 - val_accuracy: 0.9140
Epoch 7/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0223 - accuracy: 0.9939 - val_loss: 0.3731 - val_accuracy: 0.9077

In [89]:
#### Prediction

###performance metrics and accuracy 

### predict_classes use because our y_test data is in array format
y_pred=model.predict_classes(x_test)

In [90]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [1],
       [0],
       [1]], dtype=int32)

In [91]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [92]:
cm

array([[3153,  284],
       [ 228, 2370]])

In [93]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.9151615575807788

# **Adding Dropout Layer**

In [94]:
#### Creating Model
from tensorflow.keras.layers import Dropout

### Embedding Layer take input and convert into specific number of Feature of vectors
embedding_vector_feature=40
new_model=Sequential()
### Embedding Layer
new_model.add(Embedding(vocab_size,embedding_vector_feature,input_length=sent_length))
#### Adding Dropout
new_model.add(Dropout(0.3))
### Adding Lstm layer
new_model.add(LSTM(100))
#### Adding Dropout
new_model.add(Dropout(0.3))
### Addin Dense Layer because its classification problem
new_model.add(Dense(units=1,activation='sigmoid')) #### units =1 because it is classification problem and return 1 value either 0 or 1
### Model Compilation 
new_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy']) 
### model Summary
new_model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [95]:
new_model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 5s 27ms/step - loss: 0.3548 - accuracy: 0.8271 - val_loss: 0.1933 - val_accuracy: 0.9125
Epoch 2/10
192/192 [==============================] - 5s 26ms/step - loss: 0.1567 - accuracy: 0.9377 - val_loss: 0.1904 - val_accuracy: 0.9225
Epoch 3/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1195 - accuracy: 0.9530 - val_loss: 0.2064 - val_accuracy: 0.9239
Epoch 4/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0978 - accuracy: 0.9649 - val_loss: 0.2165 - val_accuracy: 0.9223
Epoch 5/10
192/192 [==============================] - 5s 26ms/step - loss: 0.0780 - accuracy: 0.9732 - val_loss: 0.2453 - val_accuracy: 0.9228
Epoch 6/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0619 - accuracy: 0.9789 - val_loss: 0.2391 - val_accuracy: 0.9160
Epoch 7/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0466 - accuracy: 0.9850 - val_loss: 0.3432 - val_accuracy: 0.9137

In [96]:
#### Prediction

###performance metrics and accuracy 

### predict_classes use because our y_test data is in array format
y_pred_new=new_model.predict_classes(x_test)

In [97]:
y_pred_new

array([[1],
       [0],
       [0],
       ...,
       [1],
       [0],
       [1]], dtype=int32)

In [98]:
from sklearn.metrics import confusion_matrix
cm_new=confusion_matrix(y_test,y_pred_new)

In [99]:
cm_new

array([[3217,  220],
       [ 380, 2218]])

In [100]:
from sklearn.metrics import accuracy_score
acc_new=accuracy_score(y_test,y_pred_new)
acc_new

0.9005799502899752